version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciadorcinema
      MYSQL_USER: cinemadmin
      MYSQL_PASSWORD: cinemadmin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  gerenciadorcinemaapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciadorcinemaapi
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;user=cinemadmin;password=cinemadmin;database=gerenciadorcinema
    ports:
      - "8000:80"

volumes:
  mysql-data:
